//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonsViewed
    {
        public int LessonViewID { get; set; }
        public string UserID { get; set; }
        public int LessonID { get; set; }
        public System.DateTime DateViewed { get; set; }
    
        public virtual Lessons Lesson { get; set; }
        public virtual UserDetails UserDetail { get; set; }
    }
}
