//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lessons()
        {
            this.LessonsVieweds = new HashSet<LessonsViewed>();
        }
    
        public int LessonID { get; set; }
        public string LessonTitle { get; set; }
        public int CourseID { get; set; }
        public string Introduction { get; set; }
        public string VideoURL { get; set; }
        public string PdfFileName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Courses Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonsViewed> LessonsVieweds { get; set; }
    }
}
